export {default as logoLight} from "./logo-1.jpg"
export {default as flag} from "./flag-eg.jpg"
export {default as car1} from "./15.jpg"
export {default as car2} from "./16.jpg"
export {default as car3} from "./17.jpg"
export {default as car4} from "./18.jpg"
export {default as cartpay2} from "./cardpay3.jpg"
export {default as cardNpg} from "./cardNpg.png"